@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Fri Nov 12 23:30:39 +0700 2021
REM SW Build 2552052 on Fri May 24 14:49:42 MDT 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_cpu_time_synth -key {Post-Synthesis:sim_1:Timing:tb_cpu} -tclbatch tb_cpu.tcl -view D:/Files/CE409/Exercise/Processor/project_cpu/tb_cpu_behav.wcfg -log simulate.log"
call xsim  tb_cpu_time_synth -key {Post-Synthesis:sim_1:Timing:tb_cpu} -tclbatch tb_cpu.tcl -view D:/Files/CE409/Exercise/Processor/project_cpu/tb_cpu_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
